"""Unit tests for the CyberDeltaEngine internal Order model and enrichment slots.

Covers:
- Order: construction, core field validation, mutability, model validation, extra='forbid'
- BackpackOrderDetails: creation, field validation (decimal, enum), immutability, extra='ignore'
- HyperliquidOrderDetails: creation, field validation, immutability, extra='ignore'
- Core+Details pattern integration.
"""

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

import pytest
from pydantic import ValidationError

from cyberdelta.core.enums import (
    OrderExpiryReason,
    OrderStatus,
    OrderUpdateOrigin,
    SelfTradePrevention,
    TriggerType,
)
from cyberdelta.core.models.market.order import (
    BackpackOrderDetails,
    HyperliquidOrderDetails,
    Order,
)
from cyberdelta.core.models.market.trade import Trade  # Needed for Order.trades
from cyberdelta.enums import OrderSide, OrderType, TimeInForce
from cyberdelta.exceptions.field_validation import TypeFieldError
from cyberdelta.exceptions.parsing import DateTimeParsingError, EmptyStringError
from tests.common_symbols import BTC_HL


pytestmark = pytest.mark.timing


# --- Helper Fixtures ---
@pytest.fixture
def valid_hl_order_details_data() -> dict[str, Any]:
    """Provide valid data for HyperliquidOrderDetails.

    Returns:
        dict[str, Any]: Valid data dictionary for HyperliquidOrderDetails testing.
    """
    return {"remaining_sz": Decimal("0.5")}


@pytest.fixture
def valid_bp_order_details_data() -> dict[str, Any]:
    """Provide valid data for BackpackOrderDetails.

    Returns:
        dict[str, Any]: Valid data dictionary for BackpackOrderDetails testing.
    """
    return {
        "executed_quote_quantity": Decimal("1000.50"),
        "self_trade_prevention": SelfTradePrevention.REJECT_TAKER,
        "expiry_reason": OrderExpiryReason.USER_CANCELLED,
        "origin": OrderUpdateOrigin.USER,
        "sl_trigger_price": Decimal("49000.0"),
        "sl_limit_price": Decimal("48950.0"),
        "sl_trigger_by": TriggerType.MARK_PRICE,
        "tp_trigger_price": Decimal("55000.0"),
        "tp_limit_price": Decimal("55050.0"),
        "tp_trigger_by": TriggerType.LAST_PRICE,
        "trigger_quantity": Decimal("1.0"),
    }


@pytest.fixture
def base_order_data() -> dict[str, Any]:
    """Provide a dictionary with valid core data for Order creation.

    Returns:
        dict[str, Any]: Valid core data dictionary for Order testing.
    """
    return {
        "exchange": "backpack",
        "symbol": BTC_HL,
        "side": OrderSide.BUY,
        "order_type": OrderType.LIMIT,
        "quantity_requested": Decimal("1.0"),
        "price": Decimal("50000.0"),
        "time_in_force": TimeInForce.GTC,
        "created_at": datetime.now(UTC),
        # Other optional fields default to None or factory defaults
    }


# --- Core Order Model Tests ---
def test_order_minimal_valid(base_order_data: dict[str, Any]) -> None:
    """Test that a minimal valid Order instance is accepted."""
    order = Order(**base_order_data)
    assert order.exchange == "backpack"
    assert order.symbol.value == "BTC-PERP"
    assert order.side == OrderSide.BUY
    assert order.order_type == OrderType.LIMIT
    assert order.quantity_requested == Decimal("1.0")
    assert order.price == Decimal("50000.0")
    assert order.time_in_force == TimeInForce.GTC
    assert order.status == OrderStatus.NEW
    assert order.quantity_filled == Decimal(0)
    assert order.reduce_only is False
    assert order.post_only is False
    assert isinstance(order.created_at, datetime)
    assert order.trades == []
    assert order.hl_details is None
    assert order.bp_details is None
    assert isinstance(uuid.UUID(order.client_order_id), uuid.UUID)
    assert order.model_config.get("frozen") is not True
    assert order.model_config.get("validate_assignment") is True
    assert order.model_config.get("extra") == "forbid"


def test_order_all_core_fields(base_order_data: dict[str, Any]) -> None:
    """Test creation with all optional core fields populated."""
    data = base_order_data.copy()
    # Use the client_order_id generated by the Order model if possible
    client_order_id_for_trade = data.get("client_order_id", str(uuid.uuid4()))

    # Construct Trade instance directly with correct types
    trade_instance = Trade(
        id="trade1",
        order_id="bp12345",  # Assume this matches exchange_order_id below
        client_order_id=client_order_id_for_trade,
        exchange="backpack",
        symbol=BTC_HL,
        side=OrderSide.BUY,
        quantity=Decimal("0.5"),
        price=Decimal("50001.0"),
        fee=Decimal("0.5"),
        fee_asset="USDC",
        executed_at=datetime.now(UTC),
        is_maker=False,
    )

    data.update(
        {
            "exchange_order_id": "bp12345",
            "related_order_id": "bp00000",
            "status": OrderStatus.PARTIALLY_FILLED,
            "quantity_filled": Decimal("0.5"),
            "quote_quantity_requested": Decimal("50000.0"),
            "average_fill_price": Decimal("50001.0"),
            "stop_price": Decimal("49000.0"),
            "trigger_by": TriggerType.MARK_PRICE,
            "reduce_only": True,
            "post_only": False,
            "updated_at": datetime.now(UTC),
            "triggered_at": None,
            "strategy_name": "TestStrat",
            "signal_id": "Sig123",
            "trades": [trade_instance],
        },
    )
    order = Order(**data)
    assert order.exchange_order_id == "bp12345"
    assert order.status == OrderStatus.PARTIALLY_FILLED
    assert order.quantity_filled == Decimal("0.5")
    assert order.average_fill_price == Decimal("50001.0")
    assert order.reduce_only is True
    assert isinstance(order.updated_at, datetime)
    assert len(order.trades) == 1
    assert order.trades[0].id == "trade1"


def test_order_required_fields_missing(base_order_data: dict[str, Any]) -> None:
    """Test that missing required core fields raise ValidationError."""
    required_fields = [
        "exchange",
        "symbol",
        "side",
        "order_type",
        "quantity_requested",
        "time_in_force",
    ]
    # price is required for LIMIT type in base_order_data
    required_fields_limit = [*required_fields, "price"]

    for field_to_remove in required_fields_limit:
        invalid_data = base_order_data.copy()
        del invalid_data[field_to_remove]
        # Remove match - just ensure ValidationError is raised
        with pytest.raises(ValidationError):
            Order(**invalid_data)


@pytest.mark.parametrize(
    ("field", "value", "error_match"),
    [
        # Strings
        ("exchange", "", r"exchange.*String should not be empty"),
        ("symbol", None, r"symbol.*Value error, symbol: Value cannot be None"),
        ("client_order_id", "   ", r"client_order_id.*String should not be empty"),
        (
            "exchange_order_id",
            "id-" * 50,
            r"exchange_order_id.*ensure this value has at most 128 characters",
        ),
        # Enums
        ("side", "INVALID", r"side.*Input should be .*BUY.* or .*SELL"),
        ("order_type", None, r"order_type.*Field required"),
        ("status", "PENDING", r"status.*Input should be .*OrderStatus"),
        ("time_in_force", "GOOD_TIL_FRIDAY", r"time_in_force.*Input should be .*TimeInForce"),
        ("trigger_by", "INDEX", r"trigger_by.*Input should be .*TriggerType"),
        # Decimals (Required, >0)
        ("quantity_requested", 0, r"quantity_requested.*Input should be greater than 0"),
        ("quantity_requested", "-1", r"quantity_requested.*Input should be greater than 0"),
        ("quantity_requested", Decimal("NaN"), r"quantity_requested.*Value must be finite"),
        # Decimals (Optional, >0)
        (
            "quote_quantity_requested",
            Decimal(0),
            r"quote_quantity_requested.*Input should be greater than 0",
        ),
        ("price", Decimal(-100), r"price.*Input should be greater than 0"),
        ("stop_price", Decimal("Infinity"), r"stop_price.*Value must be finite if provided"),
        ("average_fill_price", "abc", r"average_fill_price.*Cannot convert 'abc' to Decimal"),
        # Decimals (Required, >=0)
        (
            "quantity_filled",
            Decimal("-0.1"),
            r"quantity_filled.*Input should be greater than or equal to 0",
        ),
        (
            "quantity_filled",
            None,
            r"quantity_filled.*Value error, quantity_filled: Value cannot be None",
        ),
        # Bools - Test truly invalid inputs
        ("reduce_only", "maybe", r"reduce_only.*Input should be a valid boolean"),
        ("post_only", [True], r"post_only.*Input should be a valid boolean"),
        # Datetimes
        (
            "created_at",
            None,
            r"created_at.*Value error, created_at: Required datetime parsed as None or invalid",
        ),
        ("updated_at", "yesterday", r"updated_at.*Cannot parse ISO datetime string"),
    ],
)
def test_order_invalid_core_field_values(
    base_order_data: dict[str, Any],
    field: str,
    value: object,  # Using object instead of Any for invalid inputs
    error_match: str,
) -> None:
    """Test core field validation failures for various invalid inputs."""
    invalid_data = base_order_data.copy()
    if field == "price" and invalid_data.get("order_type") != OrderType.LIMIT:
        invalid_data["order_type"] = OrderType.LIMIT
    elif field == "stop_price" and invalid_data.get("order_type") != OrderType.STOP_MARKET:
        invalid_data["order_type"] = OrderType.STOP_MARKET

    invalid_data[field] = value

    # Handle specific business logic exceptions
    if (field == "exchange" and not value) or (field == "client_order_id" and value == "   "):
        with pytest.raises(EmptyStringError):
            Order(**invalid_data)
    elif field == "updated_at" and value == "yesterday":
        with pytest.raises(DateTimeParsingError):
            Order(**invalid_data)
    else:
        # Check if *any* validation error occurs, remove specific match
        with pytest.raises((
            ValidationError,
            ValueError,
            TypeError,
            EmptyStringError,
            DateTimeParsingError,
            TypeFieldError,
        )):
            Order(**invalid_data)


def test_order_model_validation_failures(base_order_data: dict[str, Any]) -> None:
    """Test model validation failures (cross-field logic)."""
    # Keep specific matches here as the exact validation rule is important
    # LIMIT without price
    data = base_order_data.copy()
    data["order_type"] = OrderType.LIMIT
    del data["price"]
    with pytest.raises(
        ValidationError,
        match=r"Value error, Order type LIMIT requires a positive price",
    ):
        Order(**data)

    # LIMIT with zero price
    data = base_order_data.copy()
    data["order_type"] = OrderType.LIMIT
    data["price"] = Decimal(0)
    # Remove match - field validation catches this, just ensure ValidationError
    with pytest.raises(ValidationError):
        Order(**data)

    # STOP_MARKET without stop_price
    data = base_order_data.copy()
    data["order_type"] = OrderType.STOP_MARKET
    data["price"] = None
    with pytest.raises(
        ValidationError,
        match=r"Value error, Order type STOP_MARKET requires a positive stop_price",
    ):
        Order(**data)

    # STOP_LIMIT with negative stop_price
    data = base_order_data.copy()
    data["order_type"] = OrderType.STOP_LIMIT
    data["price"] = Decimal(100)
    data["stop_price"] = Decimal(-50)
    # Remove match - field validation catches this, just ensure ValidationError
    with pytest.raises(ValidationError):
        Order(**data)

    # Filled quantity > requested quantity
    data = base_order_data.copy()
    data["quantity_filled"] = data["quantity_requested"] + Decimal("0.01")
    data["average_fill_price"] = Decimal(50000)
    with pytest.raises(
        ValidationError,
        match=r"Value error, quantity_filled .* cannot exceed quantity_requested",
    ):
        Order(**data)

    # Positive fill quantity without positive average fill price
    data = base_order_data.copy()
    data["quantity_filled"] = Decimal("0.1")
    data["average_fill_price"] = Decimal(0)
    # Remove match - field validation catches this, just ensure ValidationError
    with pytest.raises(ValidationError):
        Order(**data)
    # Setting to None triggers the model validation (keep specific match here)
    data["average_fill_price"] = None
    with pytest.raises(
        ValidationError,
        match="Value error, average_fill_price must be positive if quantity_filled > 0",
    ):
        Order(**data)

    # HL exchange with BP details
    data = base_order_data.copy()
    data["exchange"] = "hyperliquid"
    data["bp_details"] = BackpackOrderDetails()
    with pytest.raises(
        ValidationError,
        match=r"Value error, Backpack details .* must be None for a Hyperliquid order",
    ):
        Order(**data)

    # BP exchange with HL details
    data = base_order_data.copy()
    data["exchange"] = "backpack"
    data["hl_details"] = HyperliquidOrderDetails()
    with pytest.raises(
        ValidationError,
        match=r"Value error, Hyperliquid details .* must be None for a Backpack order",
    ):
        Order(**data)


def test_order_mutability(base_order_data: dict[str, Any]) -> None:
    """Test that Order is mutable and assignment triggers validation."""
    order = Order(**base_order_data)
    new_status = OrderStatus.FILLED
    new_qty_filled = order.quantity_requested
    price_base = order.price if order.price is not None else Decimal(0)
    new_avg_price = price_base + Decimal(1)

    order.status = new_status
    order.average_fill_price = new_avg_price
    order.quantity_filled = new_qty_filled
    order.updated_at = datetime.now(UTC)

    assert order.status == new_status
    assert order.quantity_filled == new_qty_filled
    assert order.average_fill_price == new_avg_price
    assert isinstance(order.updated_at, datetime)

    # Invalid assignment (violates model validator - qty filled > requested)
    with pytest.raises(
        ValidationError,
        match=r"Value error, quantity_filled .* cannot exceed quantity_requested",
    ):
        order.average_fill_price = new_avg_price + 1
        order.quantity_filled = order.quantity_requested + Decimal("0.01")
    order.quantity_filled = new_qty_filled

    # Invalid assignment (violates field validator - negative price)
    # Remove match - just ensure ValidationError
    with pytest.raises(ValidationError):
        order.price = Decimal(-100)
    order.price = price_base

    # Invalid assignment (violates model validator - avg price with zero qty)
    with pytest.raises(
        ValidationError,
        match="Value error, average_fill_price must be positive if quantity_filled > 0",
    ):
        order.quantity_filled = Decimal("0.1")
        order.average_fill_price = None
    # Reset average_fill_price before resetting quantity_filled
    order.average_fill_price = new_avg_price
    order.quantity_filled = new_qty_filled

    # Test assignment to details slot
    order.exchange = "backpack"
    order.bp_details = BackpackOrderDetails(origin=OrderUpdateOrigin.USER)
    assert order.bp_details is not None
    assert order.bp_details.origin == OrderUpdateOrigin.USER


def test_order_extra_fields_forbidden(base_order_data: dict[str, Any]) -> None:
    """Test extra='forbid' on core Order model."""
    invalid_data = base_order_data.copy()
    invalid_data["extra_order_field"] = "not allowed"
    with pytest.raises(ValidationError, match="Extra inputs are not permitted"):
        Order(**invalid_data)


# --- HyperliquidOrderDetails Tests ---


def test_hl_details_creation_and_immutability(
    valid_hl_order_details_data: dict[str, Any],
) -> None:
    """Test HyperliquidOrderDetails creation and immutability."""
    details = HyperliquidOrderDetails(**valid_hl_order_details_data)
    assert details.remaining_sz == Decimal("0.5")
    assert details.model_config.get("frozen") is True

    # Test immutability
    with pytest.raises(ValidationError, match="Instance is frozen"):
        details.remaining_sz = Decimal("0.6")


@pytest.mark.parametrize(
    ("field", "value", "error_match"),
    [
        ("remaining_sz", Decimal(-1), "Input should be greater than or equal to 0"),
        ("remaining_sz", Decimal("NaN"), "must be finite if provided"),
        ("remaining_sz", "abc", "decimal validation failed.*Cannot convert to Decimal"),
    ],
)
def test_hl_details_invalid_field_values(
    valid_hl_order_details_data: dict[str, Any],
    field: str,
    value: object,  # Using object instead of Any for invalid inputs
    error_match: str,
) -> None:
    """Test validation failures for HyperliquidOrderDetails."""
    invalid_data = valid_hl_order_details_data.copy()
    invalid_data[field] = value
    with pytest.raises(ValidationError, match=error_match):
        HyperliquidOrderDetails(**invalid_data)


def test_hl_details_extra_fields_ignored(valid_hl_order_details_data: dict[str, Any]) -> None:
    """Test extra='ignore' on HyperliquidOrderDetails."""
    data = valid_hl_order_details_data.copy()
    data["ignored_hl_field"] = 123
    details = HyperliquidOrderDetails(**data)
    assert not hasattr(details, "ignored_hl_field")


# --- BackpackOrderDetails Tests ---


def test_bp_details_creation_and_immutability(
    valid_bp_order_details_data: dict[str, Any],
) -> None:
    """Test basic creation and immutability of BackpackOrderDetails."""
    details = BackpackOrderDetails(**valid_bp_order_details_data)
    assert details.executed_quote_quantity == Decimal("1000.50")
    assert details.self_trade_prevention == SelfTradePrevention.REJECT_TAKER
    assert details.model_config.get("frozen") is True
    assert details.model_config.get("extra") == "ignore"

    # Test immutability
    with pytest.raises(ValidationError, match="Instance is frozen"):
        details.executed_quote_quantity = Decimal(2000)  # Removed unused type: ignore

    # Test creation with potentially invalid types for enums (should pass if None)
    # Corrected to use valid types (None or Enum) instead of Decimals
    invalid_type_data = valid_bp_order_details_data.copy()
    invalid_type_data["self_trade_prevention"] = None  # Pass None instead of Decimal("1")
    invalid_type_data["expiry_reason"] = None  # Pass None instead of Decimal("2")
    invalid_type_data["origin"] = None  # Pass None instead of Decimal("3")
    invalid_type_data["sl_trigger_by"] = None  # Pass None instead of Decimal("4")
    invalid_type_data["tp_trigger_by"] = None  # Pass None instead of Decimal("5")

    # This creation should now pass as None is valid for Optional Enum fields
    details_none_enums = BackpackOrderDetails(**invalid_type_data)
    assert details_none_enums.self_trade_prevention is None
    assert details_none_enums.expiry_reason is None
    assert details_none_enums.origin is None
    assert details_none_enums.sl_trigger_by is None
    assert details_none_enums.tp_trigger_by is None


@pytest.mark.parametrize(
    ("field", "value", "error_match"),
    [
        # Decimals (Optional, >=0)
        (
            "executed_quote_quantity",
            Decimal("-0.01"),
            r"executed_quote_quantity.*Input should be greater than or equal to 0",
        ),
        (
            "executed_quote_quantity",
            "invalid",
            r"executed_quote_quantity.*Cannot convert 'invalid' to Decimal",
        ),
        # Decimals (Optional, >0)
        ("sl_trigger_price", Decimal(0), r"sl_trigger_price.*Input should be greater than 0"),
        ("sl_limit_price", Decimal(-1), r"sl_limit_price.*Input should be greater than 0"),
        ("tp_trigger_price", Decimal("NaN"), r"tp_trigger_price.*Value must be finite if provided"),
        (
            "tp_limit_price",
            Decimal("Infinity"),
            r"tp_limit_price.*Value must be finite if provided",
        ),
        ("trigger_quantity", Decimal(-10), r"trigger_quantity.*Input should be greater than 0"),
        # Enums (Optional) - Use invalid string/int inputs
        (
            "self_trade_prevention",
            "REJECT_INVALID",
            r"self_trade_prevention.*Input should be .*SelfTradePrevention",
        ),
        ("expiry_reason", 999, r"expiry_reason.*Input should be .*OrderExpiryReason"),
        ("origin", "EXTERNAL_SYSTEM", r"origin.*Input should be .*OrderUpdateOrigin"),
        ("sl_trigger_by", "OraclePrice", r"sl_trigger_by.*Input should be .*TriggerType"),
        ("tp_trigger_by", None, ""),  # None is allowed
    ],
)
def test_bp_details_invalid_field_values(
    valid_bp_order_details_data: dict[str, Any],
    field: str,
    value: object,  # Using object instead of Any for invalid inputs
    error_match: str,
) -> None:
    """Test that BackpackOrderDetails rejects invalid field values."""
    invalid_data = valid_bp_order_details_data.copy()
    invalid_data[field] = value

    if error_match:
        # Check if *any* validation error occurs, remove specific match
        with pytest.raises(ValidationError):
            BackpackOrderDetails(**invalid_data)
    else:  # Expect no error
        details = BackpackOrderDetails(**invalid_data)
        assert getattr(details, field) is None


def test_bp_details_extra_fields_ignored(valid_bp_order_details_data: dict[str, Any]) -> None:
    """Test extra='ignore' on BackpackOrderDetails."""
    data = valid_bp_order_details_data.copy()
    data["ignored_bp_field"] = {"a": 1}
    details = BackpackOrderDetails(**data)
    assert not hasattr(details, "ignored_bp_field")


class TestOrderModel:
    """Test suite for the Order Pydantic model."""

    def test_update_order_status(self) -> None:
        """Test updating the order status."""
        # Use the base_order_data fixture or a minimal valid dict
        order_data: dict[str, Any] = {
            "exchange": "test_exchange",
            "symbol": BTC_HL,
            "side": OrderSide.BUY,
            "order_type": OrderType.LIMIT,
            "quantity_requested": Decimal("1.0"),
            "price": Decimal("50000.0"),
            "time_in_force": TimeInForce.GTC,
            "created_at": datetime.now(UTC),
        }
        order = Order(**order_data)  # Create and assign the order instance

        initial_status = order.status
        initial_updated_at = order.updated_at  # Store initial updated_at

        # Simulate a time delay before status update
        # In a real scenario, this would happen due to external events
        # For testing, we can manually advance time if needed, or just check timestamp changes

        order.status = OrderStatus.FILLED
        order.updated_at = datetime.now(UTC)  # Explicitly update timestamp

        assert order.status == OrderStatus.FILLED
        assert order.status != initial_status
        assert order.updated_at is not None
        # Ensure updated_at timestamp has changed or is later if initial_updated_at was None
        if initial_updated_at:
            assert order.updated_at > initial_updated_at
        else:
            # If initial_updated_at was None (e.g. for a brand new order)
            # then updated_at should now be set.
            assert order.updated_at is not None

    # Add other tests for Order model specific logic if needed
    # Example: test_order_with_hyperliquid_details, test_order_with_backpack_details


# Example of how you might test with details (adjust based on actual fixture availability)
# @pytest.mark.xfail(
# def test_order_with_hl_details(
# base_order_data: dict[str, Any],
# ) -> None:
# """Test Order creation with HyperliquidOrderDetails."""
# assert order.hl_details is not None
# assert order.bp_details is None
