"""Domain events for the trading system.

This module defines all domain events that represent significant business
occurrences in the trading system.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Optional

from pydantic import Field

from cyberdelta.application.event_bus import DomainEvent
from cyberdelta.core.symbols.models import Symbol
from cyberdelta.enums.exchange_names import ExchangeName
from cyberdelta.enums.trading import OrderSide


class OrderFilledEvent(DomainEvent):
    """Event fired when an order is filled (partially or completely).
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Uses Symbol objects, NOT strings
    - Uses ExchangeName enum, NOT strings
    - Uses Decimal for all financial values
    - NO default values for critical fields
    """
    
    order_id: str = Field(
        description="Unique identifier of the filled order"
    )
    
    symbol: Symbol = Field(
        description="Trading symbol (using Symbol object, not string)"
    )
    
    exchange: ExchangeName = Field(
        description="Exchange where the order was filled"
    )
    
    side: OrderSide = Field(
        description="Order side (BUY or SELL)"
    )
    
    fill_price: Decimal = Field(
        description="Price at which the order was filled"
    )
    
    fill_quantity: Decimal = Field(
        description="Quantity that was filled"
    )
    
    commission: Decimal = Field(
        description="Commission/fee paid for the fill"
    )
    
    remaining_quantity: Decimal = Field(
        description="Remaining unfilled quantity"
    )
    
    # Optional fields
    trade_id: Optional[str] = Field(
        default=None,
        description="Exchange-specific trade ID"
    )


class PositionUpdatedEvent(DomainEvent):
    """Event fired when a position is updated due to trade execution.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Uses Symbol objects, NOT strings
    - Uses ExchangeName enum, NOT strings
    - Uses Decimal for all quantities and prices
    """
    
    symbol: Symbol = Field(
        description="Trading symbol (using Symbol object, not string)"
    )
    
    exchange: ExchangeName = Field(
        description="Exchange where the position exists"
    )
    
    previous_quantity: Decimal = Field(
        description="Position quantity before the update"
    )
    
    new_quantity: Decimal = Field(
        description="Position quantity after the update"
    )
    
    average_price: Decimal = Field(
        description="Average entry price of the position"
    )
    
    # Optional fields
    realized_pnl: Optional[Decimal] = Field(
        default=None,
        description="Realized PnL if position was closed/reduced"
    )
    
    unrealized_pnl: Optional[Decimal] = Field(
        default=None,
        description="Current unrealized PnL of the position"
    )


class BalanceUpdatedEvent(DomainEvent):
    """Event fired when account balance is updated.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Uses Symbol objects for assets, NOT strings
    - Uses ExchangeName enum, NOT strings
    - Uses Decimal for all monetary amounts
    """
    
    asset: Symbol = Field(
        description="Asset symbol (using Symbol object, not string)"
    )
    
    exchange: ExchangeName = Field(
        description="Exchange where the balance exists"
    )
    
    previous_balance: Decimal = Field(
        description="Balance before the update"
    )
    
    new_balance: Decimal = Field(
        description="Balance after the update"
    )
    
    balance_change: Decimal = Field(
        description="Change in balance (positive = increase, negative = decrease)"
    )
    
    # Optional context
    reason: Optional[str] = Field(
        default=None,
        description="Reason for balance change (trade, transfer, etc.)"
    )


class SignalGeneratedEvent(DomainEvent):
    """Event fired when a trading signal is generated by a strategy.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Uses Symbol objects, NOT strings
    - Uses ExchangeName enum, NOT strings
    - References signal by ID, not embedded object (to avoid circular refs)
    """
    
    signal_id: str = Field(
        description="Unique identifier of the generated signal"
    )
    
    strategy_name: str = Field(
        description="Name of the strategy that generated the signal"
    )
    
    symbol: Symbol = Field(
        description="Trading symbol (using Symbol object, not string)"
    )
    
    exchange: ExchangeName = Field(
        description="Target exchange for the signal"
    )
    
    side: OrderSide = Field(
        description="Signal direction (BUY or SELL)"
    )
    
    confidence: Decimal = Field(
        description="Signal confidence score (0.0 to 1.0)"
    )
    
    # Optional signal data
    target_price: Optional[Decimal] = Field(
        default=None,
        description="Target price for the signal"
    )


class RiskLimitViolationEvent(DomainEvent):
    """Event fired when a risk limit is violated.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Explicit violation details, no vague messages
    - Uses Decimal for all monetary amounts
    - References specific signal/order by ID
    """
    
    signal_id: str = Field(
        description="ID of the signal that violated risk limits"
    )
    
    violation_type: str = Field(
        description="Type of risk limit violated (position_size, exposure, etc.)"
    )
    
    violation_details: str = Field(
        description="Specific details about the violation"
    )
    
    current_value: Decimal = Field(
        description="Current value that violated the limit"
    )
    
    limit_value: Decimal = Field(
        description="The limit that was violated"
    )
    
    # Optional context
    symbol: Optional[Symbol] = Field(
        default=None,
        description="Symbol associated with the violation"
    )
    
    exchange: Optional[ExchangeName] = Field(
        default=None,
        description="Exchange associated with the violation"
    )


class MarketDataUpdatedEvent(DomainEvent):
    """Event fired when market data is updated.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Uses Symbol objects, NOT strings
    - Uses ExchangeName enum, NOT strings
    - Minimal data in event (detailed data accessed via services)
    """
    
    symbol: Symbol = Field(
        description="Trading symbol (using Symbol object, not string)"
    )
    
    exchange: ExchangeName = Field(
        description="Exchange where the market data originated"
    )
    
    data_type: str = Field(
        description="Type of market data updated (ticker, orderbook, trade)"
    )
    
    # Optional fields
    price: Optional[Decimal] = Field(
        default=None,
        description="Latest price if applicable"
    )
    
    volume: Optional[Decimal] = Field(
        default=None,
        description="Volume if applicable"
    )


class CircuitBreakerTrippedEvent(DomainEvent):
    """Event fired when a circuit breaker is triggered.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Explicit reason for circuit breaker activation
    - NO assumptions about recovery behavior
    """
    
    breaker_type: str = Field(
        description="Type of circuit breaker (global_failures, exposure_limit, etc.)"
    )
    
    trigger_reason: str = Field(
        description="Specific reason the circuit breaker was triggered"
    )
    
    failure_count: int = Field(
        description="Number of failures that triggered the breaker"
    )
    
    threshold: int = Field(
        description="Threshold that was exceeded"
    )
    
    # Optional context
    affected_symbol: Optional[Symbol] = Field(
        default=None,
        description="Symbol affected by the circuit breaker"
    )
    
    affected_exchange: Optional[ExchangeName] = Field(
        default=None,
        description="Exchange affected by the circuit breaker"
    )


class PortfolioReconciledEvent(DomainEvent):
    """Event fired when portfolio reconciliation with exchanges is completed.
    
    IMPORTANT: Following CODING_STANDARDS.md:
    - Explicit reconciliation results
    - Uses Decimal for discrepancy amounts
    """
    
    exchange: ExchangeName = Field(
        description="Exchange that was reconciled"
    )
    
    reconciliation_status: str = Field(
        description="Result of reconciliation (success, discrepancies_found, failed)"
    )
    
    discrepancies_count: int = Field(
        description="Number of discrepancies found"
    )
    
    # Optional detailed info
    max_discrepancy_usd: Optional[Decimal] = Field(
        default=None,
        description="Largest discrepancy found in USD"
    )
    
    total_discrepancy_usd: Optional[Decimal] = Field(
        default=None,
        description="Total discrepancy amount in USD"
    )