"""Consolidated portfolio types.

This module exports all types from 4 consolidated files:
- models.py: All data models and domain objects
- protocols.py: All protocol definitions
- calculations.py: Calculation inputs/outputs and financial types
- infrastructure.py: Events, exceptions, validation, state management
"""

# ==================== Models ====================
from .models import (
    # Enums
    HealthStatus,
    PortfolioComponentType,
    # Core Models
    BalanceUpdate,
    BalanceUpdateRequest,
    CacheStatistics,
    CapitalSummary,
    ComponentHealth,
    ConfigurationData,
    ConfigurationMetadata,
    ErrorContext,
    ExchangeBalances,
    ExchangeOrders,
    ExchangePositions,
    ExchangeSummary,
    ExposureMetrics,
    ManagerStats,
    MetricsData,
    MetricsMetadata,
    OperationContext,
    OperationMetadata,
    OrderUpdate,
    OrderUpdateRequest,
    PerformanceMetrics,
    PnLSummary,
    PortfolioConfig,
    PortfolioMetrics,
    PortfolioSnapshot,
    PortfolioState,
    PortfolioSummary,
    PortfolioUpdate,
    Position,
    PositionUpdate,
    PositionUpdateRequest,
    RiskParameters,
    TradeUpdate,
    TradingSession,
    ValidationContext,
    ValidationMetadata,
    ValidationStatistics,
)

# ==================== Protocols ====================
from .protocols import (
    # Manager Protocols
    BalanceManagerProtocol,
    OrderManagerProtocol,
    PortfolioManagerProtocol,
    PositionManagerProtocol,
    StateManagerProtocol,
    # Service Protocols
    CacheServiceProtocol,
    CalculatorProtocol,
    Cacheable,
    DisposableProtocol,
    EventDispatcherProtocol,
    EventHandlerProtocol,
    InitializableProtocol,
    LockableProtocol,
    MetricsCollectorProtocol,
    PersistenceServiceProtocol,
    PortfolioServiceProtocol,
    PriceServiceProtocol,
    SerializableProtocol,
    ServiceLifecycle,
    StateContainerProtocol,
    StateStorableProtocol,
    ThreadSafeProtocol,
    TimestampedProtocol,
    ValidationMiddlewareProtocol,
    ValidationProtocol,
    ValidatorProtocol,
    # Data Models for Services
    ServiceCacheStats,
    ServiceProtocolValidationError,
    ServiceResilienceStatus,
    ServiceStateData,
    ServiceValidationResult,
    ServiceValidationStats,
)

# ==================== Calculations ====================
from .calculations import (
    # Results
    AggregatedMetrics,
    AsyncOperationResult,
    BreakdownMetrics,
    CalculationMetadata,
    CalculatorConfiguration,
    CapitalAllocation,
    CorrelationResult,
    DrawdownMetrics,
    ExchangeBreakdown,
    ExposureInput,
    ExposureResult,
    FeeBreakdown,
    OperationMetrics,
    OptimizationResult,
    PerformanceInput,
    PerformanceMetrics as PerformanceMetricsCalc,  # Alias to avoid conflict
    PerformanceResult,
    PnLAggregatorConfiguration,
    PnLBreakdown,
    PortfolioExposureResult,
    PortfolioResultError,
    PortfolioSummaryMetrics,
    PortfolioUnrealizedPnLResult,
    RealizedPnLResult,
    RealizedPnLSummaryMetrics,
    Result,
    RiskInput,
    RiskResult,
    UnrealizedPnLConfiguration,
    UnrealizedPnLResult,
    VaRCalculationResult,
)

# ==================== Infrastructure ====================
from .infrastructure import (
    # Events
    BasePortfolioEvent,
    EventFilter,
    EventHandler,
    EventMetadata,
    EventMetadataContext,
    EventPriority,
    EventType,
    PortfolioEvent,
    # Exceptions
    CalculationError,
    CalculationExceptionContext,
    CalculationInput,
    CalculationResults,
    CurrentState,
    ExceptionContext,
    IntegrityExceptionContext,
    PortfolioError,
    ServiceExceptionContext,
    StateError,
    StateExceptionContext,
    StateSnapshotException,
    ValidationError,
    # Resilience
    ResilienceError,
    ResilienceErrorType,
    ResilienceMetrics,
    ResilienceResult,
    # State Management
    StateChange,
    StateChangeType,
    StateContainer,
    StateSnapshot,
    StateSummary,
    StateUpdateResult,
    StateValidationMetadata,
    StateValidationResult,
    # Type Guards
    is_non_empty_string,
    is_non_negative_number,
    is_positive_number,
    is_sized_collection,
    is_valid_currency_code,
    is_valid_decimal_string,
    is_valid_exchange_id,
    is_valid_order_id,
    is_valid_percentage,
    is_valid_symbol,
    is_valid_timestamp,
    validate_field_types,
    validate_required_fields,
    # Validation
    ValidationCategory,
    ValidationChain,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
)

# Legacy compatibility - will be removed after migration
# Map old imports to new locations
PortfolioStateManagerProtocol = PortfolioManagerProtocol

__all__ = [
    # Models - Enums
    "HealthStatus",
    "PortfolioComponentType",
    # Models - Core
    "BalanceUpdate",
    "BalanceUpdateRequest",
    "CacheStatistics",
    "CapitalSummary",
    "ComponentHealth",
    "ConfigurationData",
    "ConfigurationMetadata",
    "ErrorContext",
    "ExchangeBalances",
    "ExchangeOrders",
    "ExchangePositions",
    "ExchangeSummary",
    "ExposureMetrics",
    "ManagerStats",
    "MetricsData",
    "MetricsMetadata",
    "OperationContext",
    "OperationMetadata",
    "OrderUpdate",
    "OrderUpdateRequest",
    "PerformanceMetrics",
    "PnLSummary",
    "PortfolioConfig",
    "PortfolioMetrics",
    "PortfolioSnapshot",
    "PortfolioState",
    "PortfolioSummary",
    "PortfolioUpdate",
    "Position",
    "PositionUpdate",
    "PositionUpdateRequest",
    "RiskParameters",
    "TradeUpdate",
    "TradingSession",
    "ValidationContext",
    "ValidationMetadata",
    "ValidationStatistics",
    # Protocols - Managers
    "BalanceManagerProtocol",
    "OrderManagerProtocol",
    "PortfolioManagerProtocol",
    "PortfolioStateManagerProtocol",  # Legacy alias
    "PositionManagerProtocol",
    "StateManagerProtocol",
    # Protocols - Services
    "CacheServiceProtocol",
    "CalculatorProtocol",
    "Cacheable",
    "DisposableProtocol",
    "EventDispatcherProtocol",
    "EventHandlerProtocol",
    "InitializableProtocol",
    "LockableProtocol",
    "MetricsCollectorProtocol",
    "PersistenceServiceProtocol",
    "PortfolioServiceProtocol",
    "PriceServiceProtocol",
    "SerializableProtocol",
    "ServiceLifecycle",
    "StateContainerProtocol",
    "StateStorableProtocol",
    "ThreadSafeProtocol",
    "TimestampedProtocol",
    "ValidationMiddlewareProtocol",
    "ValidationProtocol",
    "ValidatorProtocol",
    # Service Data Models
    "ServiceCacheStats",
    "ServiceProtocolValidationError",
    "ServiceResilienceStatus",
    "ServiceStateData",
    "ServiceValidationResult",
    "ServiceValidationStats",
    # Calculations
    "AggregatedMetrics",
    "AsyncOperationResult",
    "BreakdownMetrics",
    "CalculationMetadata",
    "CalculatorConfiguration",
    "CapitalAllocation",
    "CorrelationResult",
    "DrawdownMetrics",
    "ExchangeBreakdown",
    "ExposureInput",
    "ExposureResult",
    "FeeBreakdown",
    "OperationMetrics",
    "OptimizationResult",
    "PerformanceInput",
    "PerformanceMetricsCalc",
    "PerformanceResult",
    "PnLAggregatorConfiguration",
    "PnLBreakdown",
    "PortfolioExposureResult",
    "PortfolioResultError",
    "PortfolioSummaryMetrics",
    "PortfolioUnrealizedPnLResult",
    "RealizedPnLResult",
    "RealizedPnLSummaryMetrics",
    "Result",
    "RiskInput",
    "RiskResult",
    "UnrealizedPnLConfiguration",
    "UnrealizedPnLResult",
    "VaRCalculationResult",
    # Infrastructure - Events
    "BasePortfolioEvent",
    "EventFilter",
    "EventHandler",
    "EventMetadata",
    "EventMetadataContext",
    "EventPriority",
    "EventType",
    "PortfolioEvent",
    # Infrastructure - Exceptions
    "CalculationError",
    "CalculationExceptionContext",
    "CalculationInput",
    "CalculationResults",
    "CurrentState",
    "ExceptionContext",
    "IntegrityExceptionContext",
    "PortfolioError",
    "ServiceExceptionContext",
    "StateError",
    "StateExceptionContext",
    "StateSnapshotException",
    "ValidationError",
    # Infrastructure - Resilience
    "ResilienceError",
    "ResilienceErrorType",
    "ResilienceMetrics",
    "ResilienceResult",
    # Infrastructure - State
    "StateChange",
    "StateChangeType",
    "StateContainer",
    "StateSnapshot",
    "StateSummary",
    "StateUpdateResult",
    "StateValidationMetadata",
    "StateValidationResult",
    # Infrastructure - Type Guards
    "is_non_empty_string",
    "is_non_negative_number",
    "is_positive_number",
    "is_sized_collection",
    "is_valid_currency_code",
    "is_valid_decimal_string",
    "is_valid_exchange_id",
    "is_valid_order_id",
    "is_valid_percentage",
    "is_valid_symbol",
    "is_valid_timestamp",
    "validate_field_types",
    "validate_required_fields",
    # Infrastructure - Validation
    "ValidationCategory",
    "ValidationChain",
    "ValidationIssue",
    "ValidationResult",
    "ValidationSeverity",
]