from enum import Enum
from typing import Dict, Any, Optional, List, Union
from datetime import datetime
from dataclasses import dataclass


class SignalType(Enum):
    """Type of trading signal"""
    ENTER_LONG = "ENTER_LONG"
    EXIT_LONG = "EXIT_LONG"
    ENTER_SHORT = "ENTER_SHORT"
    EXIT_SHORT = "EXIT_SHORT"
    

class PositionStatus(Enum):
    """Status of a trading position"""
    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"


class OrderType(Enum):
    """Type of order"""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


@dataclass
class TradeOperation:
    """
    Represents a trade operation (buy or sell)
    """
    symbol: str
    operation_type: str  # "BUY" or "SELL"
    quantity: float
    price: float
    timestamp: datetime
    exchange: str
    order_type: OrderType = OrderType.MARKET
    operation_id: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class MarketData:
    """
    Represents a single market data point/candle
    """
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    additional_data: Optional[Dict[str, Any]] = None


@dataclass
class TradeSignal:
    """
    Trading signal generated by a strategy
    """
    strategy_name: str
    symbol: str
    signal_type: SignalType
    timestamp: datetime
    price: float
    quantity: Optional[float] = None
    take_profit: Optional[float] = None
    stop_loss: Optional[float] = None
    order_type: OrderType = OrderType.MARKET
    expiration: Optional[datetime] = None
    metadata: Optional[Dict[str, Any]] = None
    
    def is_valid(self) -> bool:
        """Check if the signal is valid"""
        # Basic validation
        if not self.symbol or not self.strategy_name:
            return False
        
        # Check if signal is expired
        if self.expiration and datetime.now() > self.expiration:
            return False
            
        return True
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary"""
        return {
            "strategy_name": self.strategy_name,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "timestamp": self.timestamp.isoformat(),
            "price": self.price,
            "quantity": self.quantity,
            "take_profit": self.take_profit,
            "stop_loss": self.stop_loss,
            "order_type": self.order_type.value,
            "expiration": self.expiration.isoformat() if self.expiration else None,
            "metadata": self.metadata
        }


@dataclass
class Position:
    """
    Trading position information
    """
    id: str
    strategy_name: str
    symbol: str
    entry_price: float
    quantity: float
    side: str  # "LONG" or "SHORT"
    status: PositionStatus
    open_time: datetime
    close_time: Optional[datetime] = None
    exit_price: Optional[float] = None
    take_profit: Optional[float] = None
    stop_loss: Optional[float] = None
    realized_pnl: Optional[float] = None
    fees: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None
    
    def is_active(self) -> bool:
        """Check if position is still active"""
        return self.status in [PositionStatus.PENDING, PositionStatus.OPEN, PositionStatus.PARTIAL]
    
    def calculate_unrealized_pnl(self, current_price: float) -> float:
        """Calculate unrealized profit/loss based on current price"""
        if self.side == "LONG":
            return (current_price - self.entry_price) * self.quantity
        else:  # SHORT
            return (self.entry_price - current_price) * self.quantity
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert position to dictionary"""
        return {
            "id": self.id,
            "strategy_name": self.strategy_name,
            "symbol": self.symbol,
            "entry_price": self.entry_price,
            "quantity": self.quantity,
            "side": self.side,
            "status": self.status.value,
            "open_time": self.open_time.isoformat(),
            "close_time": self.close_time.isoformat() if self.close_time else None,
            "exit_price": self.exit_price,
            "take_profit": self.take_profit,
            "stop_loss": self.stop_loss,
            "realized_pnl": self.realized_pnl,
            "fees": self.fees,
            "metadata": self.metadata
        } 