"""Portfolio exception hierarchy for comprehensive error handling."""

from .base import PortfolioCriticalError, PortfolioError
from .calculation import (
    CalculationError,
    CurrencyConversionError,
    DivisionByZeroError,
    ExposureCalculationError,
    InsufficientDataError,
    InvalidCalculationInputError,
    PnLCalculationError,
    RiskLimitExceededError,
)
from .integrity import (
    BalanceDiscrepancyError,
    CacheSizeMustBePositiveError,
    ConfigurationError,
    DataCorruptionError,
    EmptyAssetError,
    EmptyListError,
    EmptySymbolError,
    InvalidAssetCharactersError,
    InvalidAssetLengthError,
    InvalidCacheSizeError,
    InvalidExchangeError,
    InvalidMarketHoursFormatError,
    InvalidPositionError,
    InvalidSymbolCharactersError,
    InvalidSymbolLengthError,
    InvalidTimestampRangeError,
    InvalidTTLError,
    InvalidURLFormatError,
    MalformedTradeError,
    NonUniqueListError,
    OrderConstraintError,
    PortfolioIntegrityError,
    PositionSizeTooLargeError,
)
from .service import (
    CacheError,
    ExternalAPIError,
    PriceServiceError,
    RateLimitError,
    ServiceError,
    ServiceTimeoutError,
    ServiceUnavailableError,
    SymbolServiceError,
)
from .state import (
    ConcurrencyError,
    DeadlockError,
    ResultAndThenNoneErrorError,
    ResultAndThenNoneValueError,
    ResultErrorWithoutErrorError,
    ResultErrorWithValueError,
    ResultMapErrorNoneErrorError,
    ResultMapErrorNoneValueError,
    ResultMapNoneErrorError,
    ResultMapNoneValueError,
    ResultOrElseNoneErrorError,
    ResultOrElseNoneValueError,
    ResultSuccessWithErrorError,
    ResultSuccessWithoutValueError,
    ResultUnwrapErrorOnSuccessError,
    ResultUnwrapNoneErrorError,
    ResultUnwrapNoneValueError,
    ResultUnwrapOnErrorError,
    ScreenerNotInitializedError,
    ServiceNotRunningError,
    StateCorruptionError,
    StateError,
    StateNotInitializedError,
    StatePersistenceError,
    StateSynchronizationError,
    StateTransitionError,
    StateValidationError,
)


__all__ = [
    "BalanceDiscrepancyError",
    "CacheError",
    "CacheSizeMustBePositiveError",
    # Calculation exceptions
    "CalculationError",
    "ConcurrencyError",
    "ConfigurationError",
    "CurrencyConversionError",
    "DataCorruptionError",
    "DeadlockError",
    "DivisionByZeroError",
    "EmptyAssetError",
    "EmptyListError",
    "EmptySymbolError",
    "ExposureCalculationError",
    "ExternalAPIError",
    "InsufficientDataError",
    "InvalidAssetCharactersError",
    "InvalidAssetLengthError",
    "InvalidCacheSizeError",
    "InvalidCalculationInputError",
    "InvalidExchangeError",
    "InvalidMarketHoursFormatError",
    "InvalidPositionError",
    "InvalidSymbolCharactersError",
    "InvalidSymbolLengthError",
    "InvalidTTLError",
    "InvalidTimestampRangeError",
    "InvalidURLFormatError",
    # Validation exceptions
    "MalformedTradeError",
    "NonUniqueListError",
    "OrderConstraintError",
    "PnLCalculationError",
    "PortfolioCriticalError",
    # Base exceptions
    "PortfolioError",
    "PortfolioIntegrityError",
    "PositionSizeTooLargeError",
    "PriceServiceError",
    "RateLimitError",
    "ResultAndThenNoneErrorError",
    "ResultAndThenNoneValueError",
    "ResultErrorWithValueError",
    "ResultErrorWithoutErrorError",
    "ResultMapErrorNoneErrorError",
    "ResultMapErrorNoneValueError",
    "ResultMapNoneErrorError",
    "ResultMapNoneValueError",
    "ResultOrElseNoneErrorError",
    "ResultOrElseNoneValueError",
    "ResultSuccessWithErrorError",
    "ResultSuccessWithoutValueError",
    "ResultUnwrapErrorOnSuccessError",
    "ResultUnwrapNoneErrorError",
    "ResultUnwrapNoneValueError",
    "ResultUnwrapOnErrorError",
    "RiskLimitExceededError",
    # State exceptions
    "ScreenerNotInitializedError",
    # Service exceptions
    "ServiceError",
    "ServiceNotRunningError",
    "ServiceTimeoutError",
    "ServiceUnavailableError",
    "StateCorruptionError",
    # State exceptions
    "StateError",
    "StateNotInitializedError",
    "StatePersistenceError",
    "StateSynchronizationError",
    "StateTransitionError",
    "StateValidationError",
    "SymbolServiceError",
]
