"""Strategy Models for CyberDeltaEngine.

This module contains models representing trading strategy intent, signals, and arbitrage
opportunities. These are used by the strategy layer to communicate actionable ideas and
instructions to the execution and portfolio layers.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any, TypeGuard

from pydantic import Field, ValidationInfo, field_validator

from cyberdelta.core.enums import SignalType
from cyberdelta.enums import OrderSide
from cyberdelta.enums.exchange_names import ExchangeName
from cyberdelta.exceptions.field_validation import (
    DecimalFieldError,
    FieldNameMissingError,
    InvalidExchangeNameError,
    RequiredFieldError,
    TypeFieldError,
)
from cyberdelta.models.base_validators import (
    StandardModel,
    optional_datetime_validator,
    optional_decimal_validator,
    required_decimal_validator,
)
from cyberdelta.symbols.models import Symbol
from cyberdelta.utils.parsing import validate_str_field


def _is_list_of_any(v: object) -> TypeGuard[list[Any]]:
    """Type guard to check if v is a list.

    Args:
        v: The object to check

    Returns:
        True if v is a list, False otherwise
    """
    return isinstance(v, list)


class TradeSignal(StandardModel):
    """Represents an actionable trading signal generated by a strategy, intended for Risk/Execution.

    It is mutable to allow downstream enrichment or modification (e.g., quantity adjustment).

    Fields:
        signal_id (str): Unique identifier (UUID).
        symbol (Symbol): Trading symbol object.
        signal_type (SignalType): Type of signal (e.g., ENTRY, EXIT).
        side (OrderSide): Buy or sell.
        price (Decimal): Required signal price (must be positive).
        quantity (Optional[Decimal]): Optional signal quantity (must be positive if set).
            Risk/Execution may adjust this.
        exchange (Union[ExchangeName, list[ExchangeName]]): Target exchange(s).
        timestamp (datetime): Signal creation timestamp (UTC), defaults to now.
        confidence (Optional[float]): Optional confidence score (0.0 to 1.0). Uses float.
        source_strategy (Optional[str]): Optional strategy identifier.
        stop_loss (Optional[Decimal]): Optional suggested stop loss price (must be positive if set).
        take_profit (Optional[Decimal]): Optional suggested take profit price (must be positive
            if set).
        expiration (Optional[datetime]): Optional signal expiry time (UTC).
        metadata (Optional[dict[str, Any]]): Optional extra metadata.

    Notes:
        - Mutable (`validate_assignment=True`).
        - Uses `Decimal` for financial values, `float` for confidence.
        - Use is_valid() to check if the signal is still actionable based on expiration.

    """

    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: Symbol
    signal_type: SignalType
    side: OrderSide
    price: Decimal = Field(..., gt=Decimal(0))  # Required, Positive
    quantity: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    exchange: ExchangeName | list[ExchangeName]  # Required
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    confidence: float | None = None  # Optional, Float
    source_strategy: str | None = None  # Optional
    stop_loss: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    take_profit: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    expiration: datetime | None = None  # Optional
    metadata: dict[str, Any] | None = None  # Optional

    # Config: Mutable (inherited from StandardModel with validate_assignment=True)

    # Use centralized validators for common patterns
    _validate_price = required_decimal_validator("price")
    _validate_optional_decimals = optional_decimal_validator("quantity", "stop_loss", "take_profit")
    _validate_expiration = optional_datetime_validator("expiration")

    # --- Field Validators --- Field Validators --- Field Validators ---

    # Symbol validation is handled by Pydantic's type system
    # No need for a custom validator since Symbol is always valid

    @field_validator("source_strategy", mode="before")
    @classmethod
    def validate_optional_strings(cls, v: str | None, info: ValidationInfo) -> str | None:
        """Validate optional string fields are non-empty, reasonable length.

        Args:
            v: Optional string value to validate
            info: Validation context containing field information

        Returns:
            Validated string value or None if not provided

        Raises:
            FieldNameMissingError: If field name is None in validation info
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError

        # source_strategy is optional
        if v is None:
            return None  # Allow None for optional fields like source_strategy

        return validate_str_field(v, field_name=field_name, max_length=64)

    @field_validator("exchange", mode="before")
    @classmethod
    def validate_exchange(
        cls,
        v: str | list[str] | ExchangeName | list[ExchangeName] | object,
        info: ValidationInfo,
    ) -> ExchangeName | list[ExchangeName]:
        """Validate exchange is a valid ExchangeName or list of ExchangeNames.

        Args:
            v: Exchange value - string, ExchangeName, or list thereof
            info: Validation context

        Returns:
            Validated ExchangeName or list of ExchangeNames

        Raises:
            TypeFieldError: If v is not a valid type
            RequiredFieldError: If list is empty
            InvalidExchangeNameError: If invalid exchange name
        """
        field_name = "exchange"

        # Handle single exchange
        if isinstance(v, ExchangeName):
            return v
        if isinstance(v, str):
            try:
                return ExchangeName(v.lower())
            except ValueError as e:
                raise InvalidExchangeNameError(
                    value=v,
                    valid_exchanges=[ex.value for ex in ExchangeName],
                ) from e

        # Handle list of exchanges
        if _is_list_of_any(v):
            if not v:
                raise RequiredFieldError(
                    field_name=field_name,
                    context="list cannot be empty",
                )
            validated_list: list[ExchangeName] = []
            for idx, item in enumerate(v):
                if isinstance(item, ExchangeName):
                    validated_list.append(item)
                elif isinstance(item, str):
                    try:
                        validated_list.append(ExchangeName(item.lower()))
                    except ValueError as e:
                        raise InvalidExchangeNameError(
                            value=item,
                            valid_exchanges=[ex.value for ex in ExchangeName],
                            context=f"index {idx}",
                        ) from e
                else:
                    raise TypeFieldError(
                        field_name=f"{field_name}[{idx}]",
                        expected_type="string or ExchangeName",
                        actual_type=type(item).__name__,
                        actual_value=item,
                    )
            return validated_list

        raise TypeFieldError(
            field_name=field_name,
            expected_type="ExchangeName, string, or list thereof",
            actual_type=type(v).__name__,
        )

    @field_validator("confidence", mode="before")
    @classmethod
    def validate_optional_float(
        cls,
        v: str | float | None,
        info: ValidationInfo,
    ) -> float | None:
        """Validate optional float value.

        Args:
            v: Optional value to convert to float
            info: Validation context

        Returns:
            Float value or None

        Raises:
            FieldNameMissingError: If field name is None in validation info
            DecimalFieldError: If value cannot be converted to float
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError
        if v is None:
            return None
        try:
            return float(v)
            # Optional: Add range check e.g., if 0.0 <= float_val <= 1.0:
        except (ValueError, TypeError) as e:
            raise DecimalFieldError(
                field_name=field_name,
                value=v,
                reason=f"Invalid float value: {v!r}. Error: {e}",
            ) from e

    def is_valid(self) -> bool:
        """Check if the signal is still valid (e.g., not expired).

        Returns:
            bool: True if not expired, False otherwise.

        """
        if self.expiration is None:
            return True
        # Ensure comparison is timezone-aware (UTC)
        return datetime.now(UTC) < self.expiration
