"""Strategy Models for CyberDeltaEngine.

This module contains models representing trading strategy intent, signals, and arbitrage
opportunities. These are used by the strategy layer to communicate actionable ideas and
instructions to the execution and portfolio layers.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any, TypeGuard

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator

from cyberdelta.core.enums import SignalType
from cyberdelta.core.symbols.models import Symbol, BaseSymbol
from cyberdelta.enums import OrderSide
from cyberdelta.exceptions.field_validation import (
    DecimalFieldError,
    DecimalFiniteError,
    FieldNameMissingError,
    ListFieldError,
    RequiredFieldError,
    TypeFieldError,
)
from cyberdelta.utils.parsing import parse_datetime_utc, parse_decimal_value, validate_str_field


def _is_list_of_any(v: object) -> TypeGuard[list[Any]]:
    """Type guard to check if v is a list.

    Args:
        v: The object to check

    Returns:
        True if v is a list, False otherwise
    """
    return isinstance(v, list)


class TradeSignal(BaseModel):
    """Represents an actionable trading signal generated by a strategy, intended for Risk/Execution.

    It is mutable to allow downstream enrichment or modification (e.g., quantity adjustment).

    Fields:
        signal_id (str): Unique identifier (UUID).
        symbol (Symbol): Trading symbol object.
        signal_type (SignalType): Type of signal (e.g., ENTRY, EXIT).
        side (OrderSide): Buy or sell.
        price (Decimal): Required signal price (must be positive).
        quantity (Optional[Decimal]): Optional signal quantity (must be positive if set).
            Risk/Execution may adjust this.
        exchange (Union[str, list[str]]): Target exchange(s).
        timestamp (datetime): Signal creation timestamp (UTC), defaults to now.
        confidence (Optional[float]): Optional confidence score (0.0 to 1.0). Uses float.
        source_strategy (Optional[str]): Optional strategy identifier.
        stop_loss (Optional[Decimal]): Optional suggested stop loss price (must be positive if set).
        take_profit (Optional[Decimal]): Optional suggested take profit price (must be positive
            if set).
        expiration (Optional[datetime]): Optional signal expiry time (UTC).
        metadata (Optional[dict[str, Any]]): Optional extra metadata.

    Notes:
        - Mutable (`validate_assignment=True`).
        - Uses `Decimal` for financial values, `float` for confidence.
        - Use is_valid() to check if the signal is still actionable based on expiration.

    """

    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: Symbol
    signal_type: SignalType
    side: OrderSide
    price: Decimal = Field(..., gt=Decimal(0))  # Required, Positive
    quantity: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    exchange: str | list[str]  # Required
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    confidence: float | None = None  # Optional, Float
    source_strategy: str | None = None  # Optional
    stop_loss: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    take_profit: Decimal | None = Field(default=None, gt=Decimal(0))  # Optional, Positive if set
    expiration: datetime | None = None  # Optional
    metadata: dict[str, Any] | None = None  # Optional

    model_config = ConfigDict(extra="forbid", validate_assignment=True)  # Mutable

    # --- Field Validators --- Field Validators --- Field Validators ---

    @field_validator("symbol", mode="before")
    @classmethod
    def validate_symbol(cls, v: Symbol) -> Symbol:
        """Validate symbol field is Symbol domain object.

        Returns:
            Symbol: The validated Symbol object.

        Raises:
            ValueError: If not a Symbol object.
        """
        if not isinstance(v, BaseSymbol):
            raise ValueError(f"Symbol must be Symbol, got {type(v).__name__}")
        return v

    @field_validator("source_strategy", mode="before")
    @classmethod
    def validate_optional_strings(cls, v: str | None, info: ValidationInfo) -> str | None:
        """Validate optional string fields are non-empty, reasonable length.

        Args:
            v: Optional string value to validate
            info: Validation context containing field information

        Returns:
            Validated string value or None if not provided

        Raises:
            FieldNameMissingError: If field name is None in validation info
            RequiredFieldError: If symbol field is None (symbol is required)
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError

        # source_strategy is optional
        if v is None:
            return None  # Allow None for optional fields like source_strategy

        return validate_str_field(v, field_name=field_name, max_length=64)

    @field_validator("exchange", mode="before")
    @classmethod
    def validate_exchange(
        cls,
        v: str | list[str] | object,
        info: ValidationInfo,
    ) -> str | list[str]:
        """Validate exchange is a non-empty str or a list of non-empty strs.

        Args:
            v: Exchange value - either a string or list of strings
            info: Validation context

        Returns:
            Validated string or list of strings

        Raises:
            TypeFieldError: If v is not a string or list of strings
            RequiredFieldError: If list is empty
            ListFieldError: If list item is not a string
        """
        field_name = "exchange"
        # DEFENSIVE CHECK: Pydantic "before" mode receives raw input, type annotation is target type
        if isinstance(v, str):
            return validate_str_field(v, field_name=field_name, max_length=64)
        if _is_list_of_any(v):
            if not v:
                raise RequiredFieldError(
                    field_name=field_name,
                    context="list cannot be empty",
                )
            validated_list: list[str] = []
            # After type guard, v is known to be list[Any]
            for idx, item in enumerate(v):
                # DEFENSIVE CHECK: List items could be any type in raw input
                if type(item) is not str:
                    raise ListFieldError(
                        field_name=field_name,
                        actual_type=type(item).__name__,
                        item_index=idx,
                        expected_item_type="string",
                    )
                validated_item = validate_str_field(
                    item,
                    field_name=f"{field_name}[{idx}]",
                    max_length=64,
                )
                validated_list.append(validated_item)
            return validated_list
        raise TypeFieldError(
            field_name=field_name,
            expected_type="string or list of strings",
            actual_type=type(v).__name__,
        )

    @field_validator("price", mode="before")
    @classmethod
    def parse_required_decimal_finite(
        cls,
        v: str | float | Decimal,
        info: ValidationInfo,
    ) -> Decimal:
        """Parse required decimal, ensuring finite. Positive check via Field.

        Args:
            v: Value to parse as decimal
            info: Validation context

        Returns:
            Parsed and validated Decimal value

        Raises:
            FieldNameMissingError: If field name is None in validation info
            DecimalFiniteError: If parsed decimal is not finite (inf/nan)
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError
        parsed = parse_decimal_value(v, field_name=field_name, allow_none=False)
        # allow_none=False ensures parsed is never None
        if not parsed.is_finite():
            raise DecimalFiniteError(field_name=field_name, value=parsed)
        return parsed

    @field_validator("quantity", "stop_loss", "take_profit", mode="before")
    @classmethod
    def parse_optional_decimal_finite(
        cls,
        v: str | float | Decimal | None,
        info: ValidationInfo,
    ) -> Decimal | None:
        """Parse optional decimal, ensuring finite if not None. Positive check via Field.

        Args:
            v: Optional value to parse as decimal
            info: Validation context

        Returns:
            Parsed Decimal value or None

        Raises:
            FieldNameMissingError: If field name is None in validation info
            DecimalFiniteError: If parsed decimal is not finite (inf/nan)
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError
        if v is None:
            return None
        parsed = parse_decimal_value(v, field_name=field_name, allow_none=True)
        if parsed is None:
            return None  # Invalid format for optional field
        if not parsed.is_finite():
            raise DecimalFiniteError(
                field_name=field_name,
                value=parsed,
                context="if provided",
            )
        return parsed

    @field_validator("confidence", mode="before")
    @classmethod
    def validate_optional_float(
        cls,
        v: str | float | None,
        info: ValidationInfo,
    ) -> float | None:
        """Validate optional float value.

        Args:
            v: Optional value to convert to float
            info: Validation context

        Returns:
            Float value or None

        Raises:
            FieldNameMissingError: If field name is None in validation info
            DecimalFieldError: If value cannot be converted to float
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError
        if v is None:
            return None
        try:
            return float(v)
            # Optional: Add range check e.g., if 0.0 <= float_val <= 1.0:
        except (ValueError, TypeError) as e:
            raise DecimalFieldError(
                field_name=field_name,
                value=v,
                reason=f"Invalid float value: {v!r}. Error: {e}",
            ) from e

    @field_validator("expiration", mode="before")
    @classmethod
    def parse_optional_datetime_utc(
        cls,
        v: str | float | datetime | None,
        info: ValidationInfo,
    ) -> datetime | None:
        """Parse optional datetime, ensuring UTC if present.

        Args:
            v: Optional datetime value in various formats
            info: Validation context

        Returns:
            UTC datetime or None

        Raises:
            FieldNameMissingError: If field name is None in validation info
        """
        field_name = info.field_name
        if field_name is None:
            raise FieldNameMissingError
        if v is None:
            return None
        return parse_datetime_utc(v, field_name=field_name)

    def is_valid(self) -> bool:
        """Check if the signal is still valid (e.g., not expired).

        Returns:
            bool: True if not expired, False otherwise.

        """
        if self.expiration is None:
            return True
        # Ensure comparison is timezone-aware (UTC)
        return datetime.now(UTC) < self.expiration
