"""
Strategy Models for CyberDeltaEngine

This module contains models representing trading strategy intent, signals, and arbitrage
opportunities. These are used by the strategy layer to communicate actionable ideas and
instructions to the execution and portfolio layers.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator

from cyberdelta.utils.parsing import parse_datetime_utc, parse_decimal_value, validate_str_field

from .enums import OrderSide, SignalType


class TradeSignal(BaseModel):
    """
    Represents an actionable trading signal generated by a strategy, intended for Risk/Execution.
    It is mutable to allow downstream enrichment or modification (e.g., quantity adjustment).

    Fields:
        signal_id (str): Unique identifier (UUID).
        symbol (str): Trading symbol (e.g., 'BTC-PERP').
        signal_type (SignalType): Type of signal (e.g., ENTRY, EXIT).
        side (OrderSide): Buy or sell.
        price (Decimal): Required signal price (must be positive).
        quantity (Optional[Decimal]): Optional signal quantity (must be positive if set).
            Risk/Execution may adjust this.
        exchange (Union[str, list[str]]): Target exchange(s).
        timestamp (datetime): Signal creation timestamp (UTC), defaults to now.
        confidence (Optional[float]): Optional confidence score (0.0 to 1.0). Uses float.
        source_strategy (Optional[str]): Optional strategy identifier.
        stop_loss (Optional[Decimal]): Optional suggested stop loss price (must be positive if set).
        take_profit (Optional[Decimal]): Optional suggested take profit price (must be positive
            if set).
        expiration (Optional[datetime]): Optional signal expiry time (UTC).
        metadata (Optional[dict[str, Any]]): Optional extra metadata.

    Notes:
        - Mutable (`validate_assignment=True`).
        - Uses `Decimal` for financial values, `float` for confidence.
        - Use is_valid() to check if the signal is still actionable based on expiration.
    """

    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    signal_type: SignalType
    side: OrderSide
    price: Decimal = Field(..., gt=Decimal("0"))  # Required, Positive
    quantity: Decimal | None = Field(default=None, gt=Decimal("0"))  # Optional, Positive if set
    exchange: str | list[str]  # Required
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    confidence: float | None = None  # Optional, Float
    source_strategy: str | None = None  # Optional
    stop_loss: Decimal | None = Field(default=None, gt=Decimal("0"))  # Optional, Positive if set
    take_profit: Decimal | None = Field(default=None, gt=Decimal("0"))  # Optional, Positive if set
    expiration: datetime | None = None  # Optional
    metadata: dict[str, Any] | None = None  # Optional

    model_config = ConfigDict(extra="forbid", validate_assignment=True)  # Mutable

    # --- Field Validators --- Field Validators --- Field Validators ---

    @field_validator("symbol", "source_strategy", mode="before")
    @classmethod
    def validate_optional_strings(cls, v: str | None, info: ValidationInfo) -> str | None:
        """Validate optional string fields are non-empty, reasonable length."""
        field_name = info.field_name
        if field_name is None:
            raise ValueError("Field name is unexpectedly None during validation.")

        # symbol is required (will fail if v is None), source_strategy is optional
        if v is None:
            if field_name == "symbol":
                raise ValueError(f"{field_name} cannot be None.")
            return None  # Allow None for optional fields like source_strategy

        return validate_str_field(v, field_name=field_name, max_length=64)

    @field_validator("exchange", mode="before")
    @classmethod
    def validate_exchange(cls, v: str | list[str], info: ValidationInfo) -> str | list[str]:
        """Validate exchange is a non-empty str or a list of non-empty strs."""
        field_name = "exchange"
        if isinstance(v, str):  # Mypy doesn't see this as redundant for raw input
            return validate_str_field(v, field_name=field_name, max_length=64)
        elif isinstance(v, list):  # Mypy doesn't see this as redundant for raw input
            if not v:
                raise ValueError(f"{field_name} list cannot be empty.")
            validated_list: list[str] = []  # Explicit type hint
            for idx, item in enumerate(v):
                if not isinstance(item, str):  # Mypy doesn't see this as redundant for raw input
                    raise TypeError(f"{field_name} list item {idx} must be a string.")
                validated_list.append(
                    validate_str_field(item, field_name=f"{field_name}[{idx}]", max_length=64)
                )
            return validated_list
        else:
            raise TypeError(f"{field_name} must be a string or a list of strings.")

    @field_validator("price", mode="before")
    @classmethod
    def parse_required_decimal_finite(
        cls, v: str | int | float | Decimal, info: ValidationInfo
    ) -> Decimal:
        """Parse required decimal, ensuring finite. Positive check via Field."""
        field_name = info.field_name
        if field_name is None:
            raise ValueError("Field name missing.")
        parsed = parse_decimal_value(v, field_name=field_name, allow_none=False)
        if parsed is None:
            raise ValueError(f"{field_name}: Required value invalid.")
        if not parsed.is_finite():
            raise ValueError(f"{field_name}: Must be finite.")
        return parsed

    @field_validator("quantity", "stop_loss", "take_profit", mode="before")
    @classmethod
    def parse_optional_decimal_finite(
        cls, v: str | int | float | Decimal | None, info: ValidationInfo
    ) -> Decimal | None:
        """Parse optional decimal, ensuring finite if not None. Positive check via Field."""
        field_name = info.field_name
        if field_name is None:
            raise ValueError("Field name missing.")
        if v is None:
            return None
        parsed = parse_decimal_value(v, field_name=field_name, allow_none=True)
        if parsed is None:
            return None  # Invalid format for optional field
        if not parsed.is_finite():
            raise ValueError(f"{field_name}: Must be finite if provided.")
        return parsed

    @field_validator("confidence", mode="before")
    @classmethod
    def validate_optional_float(
        cls, v: str | int | float | None, info: ValidationInfo
    ) -> float | None:
        """Validate optional float value."""
        field_name = info.field_name
        if field_name is None:
            raise ValueError("Field name missing.")
        if v is None:
            return None
        try:
            float_val = float(v)
            # Optional: Add range check e.g., if 0.0 <= float_val <= 1.0:
            return float_val
        except (ValueError, TypeError) as e:
            raise ValueError(f"{field_name}: Invalid float value: {v!r}. Error: {e}") from e

    @field_validator("expiration", mode="before")
    @classmethod
    def parse_optional_datetime_utc(
        cls, v: str | int | float | datetime | None, info: ValidationInfo
    ) -> datetime | None:
        """Parse optional datetime, ensuring UTC if present."""
        field_name = info.field_name
        if field_name is None:
            raise ValueError("Field name missing.")
        if v is None:
            return None
        dt = parse_datetime_utc(v, field_name=field_name)
        return dt  # Returns None if parsing fails, which is okay for optional

    def is_valid(self) -> bool:
        """
        Check if the signal is still valid (e.g., not expired).
        Returns:
            bool: True if not expired, False otherwise.
        """
        if self.expiration is None:
            return True
        # Ensure comparison is timezone-aware (UTC)
        return datetime.now(UTC) < self.expiration
