"""Property-based tests for the CyberDeltaEngine internal TradeSignal model.

This module provides comprehensive property-based testing of the TradeSignal Pydantic model,
which represents actionable trading signals generated by strategies for Risk/Execution layers.

Key Testing Areas:
- Field validation and type safety using property-based input generation
- Trading signal constraints and business rules validation
- Exchange field handling (single vs multiple exchanges)
- Financial precision handling for prices and quantities
- Signal expiration and validity checking over time
- Confidence scoring and metadata handling
- Mutability properties and assignment validation
- Signal generation with realistic trading scenarios

Following TESTING_SECURITY_RULES.md:
- NO hardcoded trading values (Hypothesis generates them)
- NO fallback mechanisms with arbitrary values
- Uses property-based testing for comprehensive coverage
- Tests complete signal generation flows with real constraints
- Validates financial calculation invariants and business rules

Architecture Compliance:
- Follows RULE-ARCH-MODEL-DESIGN-V2 for strict model separation
- Implements RULE-RUNTIME-SAFETY-V4 for Decimal usage and validation
- Adheres to RULE-NO-SILENCING-V4 for type safety without suppressions
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any

import pytest
from hypothesis import given, settings, strategies as st
from pydantic import ValidationError

from cyberdelta.enums import OrderSide, SignalType
from cyberdelta.enums.exchange_names import ExchangeName
from cyberdelta.exceptions.field_validation import ListFieldError, TypeFieldError
from cyberdelta.exceptions.parsing import (
    DateTimeParsingError,
    TimestampFormatError,
)
from cyberdelta.models.trade_signal import TradeSignal
from tests.common_symbols import (
    BTC_BP,
    BTC_HL,
    BTC_USDC_BP,
    DOGE_HL,
    ETH_BP,
    ETH_HL,
    ETH_USDC_BP,
    SOL_BP,
    SOL_HL,
    SOL_USDC_BP,
)


pytestmark = pytest.mark.timing


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def _is_valid_decimal_string(s: str) -> bool:
    """Check if a string can be parsed as a valid Decimal."""
    try:
        Decimal(s)
        return True
    except:
        return False


# =============================================================================
# HYPOTHESIS STRATEGIES FOR TRADE SIGNAL DATA
# =============================================================================


@st.composite
def price_strategy(draw: st.DrawFn) -> Decimal:
    """Generate realistic price values for trading signals.

    Args:
        draw: Hypothesis draw function

    Returns:
        Decimal: A valid price for trading signals (must be > 0)
    """
    value = draw(
        st.floats(
            min_value=0.00001,
            max_value=1000000.0,
            allow_infinity=False,
            allow_nan=False,
        )
    )
    return Decimal(str(value))


@st.composite
def quantity_strategy(draw: st.DrawFn) -> Decimal:
    """Generate realistic quantity values for trading signals.

    Args:
        draw: Hypothesis draw function

    Returns:
        Decimal: A valid quantity for trading signals (must be > 0)
    """
    value = draw(
        st.floats(
            min_value=0.00000001,
            max_value=1000000.0,
            allow_infinity=False,
            allow_nan=False,
        )
    )
    return Decimal(str(value))


@st.composite
def confidence_strategy(draw: st.DrawFn) -> float:
    """Generate realistic confidence values for trading signals.

    Args:
        draw: Hypothesis draw function

    Returns:
        float: A valid confidence score (0.0 to 1.0)
    """
    return draw(st.floats(min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False))


@st.composite
def valid_symbol_strategy(draw: st.DrawFn) -> Any:
    """Generate valid Symbol objects for trade signal testing.

    Args:
        draw: Hypothesis draw function

    Returns:
        Symbol: A valid symbol for trade signal data
    """
    return draw(
        st.sampled_from([
            BTC_HL,
            ETH_HL,
            SOL_HL,
            DOGE_HL,
            BTC_BP,
            ETH_BP,
            SOL_BP,
            BTC_USDC_BP,
            ETH_USDC_BP,
            SOL_USDC_BP,
        ])
    )


@st.composite
def valid_timestamp_strategy(draw: st.DrawFn) -> datetime:
    """Generate valid UTC timestamps for trade signal data.

    Args:
        draw: Hypothesis draw function

    Returns:
        datetime: A valid UTC timestamp
    """
    naive_dt = draw(
        st.datetimes(
            min_value=datetime(2020, 1, 1, tzinfo=UTC),
            max_value=datetime(2030, 12, 31, tzinfo=UTC),
        )
    )
    return naive_dt.replace(tzinfo=UTC)


@st.composite
def signal_type_strategy(draw: st.DrawFn) -> SignalType:
    """Generate valid signal types for trading signals.

    Args:
        draw: Hypothesis draw function

    Returns:
        SignalType: A valid signal type
    """
    return draw(st.sampled_from(list(SignalType)))


@st.composite
def order_side_strategy(draw: st.DrawFn) -> OrderSide:
    """Generate valid order sides for trading signals.

    Args:
        draw: Hypothesis draw function

    Returns:
        OrderSide: A valid order side (BUY or SELL)
    """
    return draw(st.sampled_from(list(OrderSide)))


@st.composite
def exchange_strategy(draw: st.DrawFn) -> ExchangeName | list[ExchangeName]:
    """Generate valid exchange values (single or list).

    Args:
        draw: Hypothesis draw function

    Returns:
        ExchangeName or list[ExchangeName]: Valid exchange configuration
    """
    exchanges = list(ExchangeName)

    if draw(st.booleans()):
        # Single exchange
        return draw(st.sampled_from(exchanges))
    # List of exchanges (1-3 exchanges)
    num_exchanges = draw(st.integers(min_value=1, max_value=min(3, len(exchanges))))
    return draw(
        st.lists(
            st.sampled_from(exchanges),
            min_size=num_exchanges,
            max_size=num_exchanges,
            unique=True,
        )
    )


@st.composite
def strategy_name_strategy(draw: st.DrawFn) -> str:
    """Generate valid strategy names.

    Args:
        draw: Hypothesis draw function

    Returns:
        str: A valid strategy name
    """
    return draw(
        st.text(
            alphabet=st.characters(
                whitelist_categories=("Lu", "Ll", "Nd"), whitelist_characters="-_"
            ),
            min_size=1,
            max_size=64,
        ).filter(lambda x: len(x.strip()) > 0)
    )


@st.composite
def metadata_strategy(draw: st.DrawFn) -> dict[str, Any]:
    """Generate valid metadata dictionaries.

    Args:
        draw: Hypothesis draw function

    Returns:
        dict[str, Any]: Valid metadata for trade signals
    """
    # Generate 0-5 key-value pairs
    num_items = draw(st.integers(min_value=0, max_value=5))

    if num_items == 0:
        return {}

    keys = draw(
        st.lists(
            st.text(
                min_size=1, max_size=20, alphabet=st.characters(whitelist_categories=("Lu", "Ll"))
            ),
            min_size=num_items,
            max_size=num_items,
            unique=True,
        )
    )

    values = draw(
        st.lists(
            st.one_of(
                st.text(max_size=50),
                st.integers(),
                st.floats(allow_nan=False, allow_infinity=False),
                st.booleans(),
            ),
            min_size=num_items,
            max_size=num_items,
        )
    )

    return dict(zip(keys, values, strict=False))


# =============================================================================
# PROPERTY TESTS FOR TRADE SIGNAL MODEL
# =============================================================================


class TestTradeSignalModelProperties:
    """Property-based tests for the TradeSignal model."""

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
    )
    @settings(max_examples=200, deadline=None)
    def test_minimal_trade_signal_creation_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
    ) -> None:
        """Property: Minimal TradeSignal with only required fields should always be valid."""
        signal = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
        )

        # Properties: Required fields should be set correctly
        assert signal.symbol == symbol
        assert signal.signal_type == signal_type
        assert signal.side == side
        assert signal.price == price
        assert signal.exchange == exchange

        # Properties: Optional fields should have correct defaults
        assert signal.quantity is None
        assert signal.confidence is None
        assert signal.source_strategy is None
        assert signal.stop_loss is None
        assert signal.take_profit is None
        assert signal.expiration is None
        assert signal.metadata is None

        # Properties: Auto-generated fields should be valid
        assert isinstance(signal.timestamp, datetime)
        assert signal.timestamp.tzinfo == UTC
        assert isinstance(uuid.UUID(signal.signal_id), uuid.UUID)

        # Property: Signal without expiration should always be valid
        assert signal.is_valid() is True

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        quantity=quantity_strategy(),
        exchange=exchange_strategy(),
        timestamp=valid_timestamp_strategy(),
        confidence=confidence_strategy(),
        source_strategy=strategy_name_strategy(),
        stop_loss=price_strategy(),
        take_profit=price_strategy(),
        metadata=metadata_strategy(),
    )
    @settings(max_examples=200, deadline=None)
    def test_complete_trade_signal_creation_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        quantity: Decimal,
        exchange: ExchangeName | list[ExchangeName],
        timestamp: datetime,
        confidence: float,
        source_strategy: str,
        stop_loss: Decimal,
        take_profit: Decimal,
        metadata: dict[str, Any],
    ) -> None:
        """Property: Complete TradeSignal with all fields should maintain data integrity."""
        # Generate an expiration time in the future
        expiration = timestamp + timedelta(minutes=30)

        signal = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            quantity=quantity,
            exchange=exchange,
            timestamp=timestamp,
            confidence=confidence,
            source_strategy=source_strategy,
            stop_loss=stop_loss,
            take_profit=take_profit,
            expiration=expiration,
            metadata=metadata,
        )

        # Properties: All fields should be preserved exactly
        assert signal.symbol == symbol
        assert signal.signal_type == signal_type
        assert signal.side == side
        assert signal.price == price
        assert signal.quantity == quantity
        assert signal.exchange == exchange
        assert signal.timestamp == timestamp
        assert signal.confidence == confidence
        assert signal.source_strategy == source_strategy
        assert signal.stop_loss == stop_loss
        assert signal.take_profit == take_profit
        assert signal.expiration == expiration
        assert signal.metadata == metadata

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
        offset_minutes=st.integers(min_value=1, max_value=60),
    )
    @settings(max_examples=150, deadline=None)
    def test_signal_expiration_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
        offset_minutes: int,
    ) -> None:
        """Property: Signal expiration should correctly determine validity."""
        now = datetime.now(UTC)

        # Future expiration - should be valid
        future_expiration = now + timedelta(minutes=offset_minutes)
        signal_future = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
            expiration=future_expiration,
        )

        # Property: Future expiration means signal is valid
        assert signal_future.is_valid() is True

        # Past expiration - should be invalid
        past_expiration = now - timedelta(minutes=offset_minutes)
        signal_past = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
            expiration=past_expiration,
        )

        # Property: Past expiration means signal is invalid
        assert signal_past.is_valid() is False

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
        new_quantity=quantity_strategy(),
        new_confidence=confidence_strategy(),
        new_strategy=strategy_name_strategy(),
    )
    @settings(max_examples=150, deadline=None)
    def test_trade_signal_mutability_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
        new_quantity: Decimal,
        new_confidence: float,
        new_strategy: str,
    ) -> None:
        """Property: TradeSignal should be mutable and validate on assignment."""
        signal = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
        )

        # Property: Valid mutations should be allowed
        signal.quantity = new_quantity
        assert signal.quantity == new_quantity

        signal.confidence = new_confidence
        assert signal.confidence == new_confidence

        signal.source_strategy = new_strategy
        assert signal.source_strategy == new_strategy

        # Property: Exchange can be updated to different valid values
        if isinstance(exchange, list) and len(exchange) > 1:
            # Change to single exchange
            signal.exchange = exchange[0]
            assert signal.exchange == exchange[0]
        else:
            # Change to list of exchanges
            signal.exchange = [ExchangeName.HYPERLIQUID, ExchangeName.BACKPACK]
            assert signal.exchange == [ExchangeName.HYPERLIQUID, ExchangeName.BACKPACK]

    @given(
        field_name=st.sampled_from(["price", "quantity", "stop_loss", "take_profit"]),
        invalid_value=st.one_of(
            st.just(Decimal(0)),
            st.just(Decimal("-0.001")),
            st.just(Decimal("NaN")),
            st.just(Decimal("Infinity")),
            st.just(Decimal("-Infinity")),
        ),
    )
    @settings(max_examples=100, deadline=None)
    def test_decimal_field_validation_properties(
        self, field_name: str, invalid_value: Decimal
    ) -> None:
        """Property: Decimal fields should reject invalid values according to constraints."""
        base_kwargs: dict[str, Any] = {
            "symbol": BTC_HL,
            "signal_type": SignalType.ENTER_LONG,
            "side": OrderSide.BUY,
            "price": Decimal("100.0"),
            "exchange": ExchangeName.HYPERLIQUID,
        }

        kwargs = base_kwargs.copy()
        kwargs[field_name] = invalid_value

        # Property: Invalid decimal values should be rejected
        with pytest.raises(ValidationError):
            TradeSignal(**kwargs)

    @given(
        parseable_inputs=st.one_of(
            st.integers(min_value=1, max_value=1000000),
            st.floats(min_value=0.0001, max_value=1000000.0, allow_nan=False, allow_infinity=False),
            st.text(alphabet="0123456789.", min_size=1, max_size=20).filter(
                lambda x: (
                    # Must have digits
                    any(c.isdigit() for c in x)
                    # Can have at most one decimal point
                    and x.count(".") <= 1
                    # Must be parseable as decimal
                    and _is_valid_decimal_string(x)
                    # Must be positive
                    and float(x) > 0
                )
            ),
        ),
    )
    @settings(max_examples=200, deadline=None)
    def test_decimal_parsing_properties(self, parseable_inputs: Any) -> None:
        """Property: TradeSignal should correctly parse various numeric input types to Decimal."""
        signal = TradeSignal(
            symbol=BTC_HL,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=parseable_inputs,
            quantity=parseable_inputs,
            stop_loss=parseable_inputs,
            take_profit=parseable_inputs,
            exchange=ExchangeName.HYPERLIQUID,
        )

        # Property: All price fields should be converted to Decimal
        assert isinstance(signal.price, Decimal)
        assert isinstance(signal.quantity, Decimal)
        assert isinstance(signal.stop_loss, Decimal)
        assert isinstance(signal.take_profit, Decimal)

        # Property: All values should be positive
        assert signal.price > 0
        assert signal.quantity > 0
        assert signal.stop_loss > 0
        assert signal.take_profit > 0

    @given(
        confidence_input=st.one_of(
            st.floats(min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False),
            st.integers(min_value=0, max_value=1),
            st.text(alphabet="0123456789.", min_size=1, max_size=10).filter(
                lambda x: (
                    x.replace(".", "").isdigit() and x.count(".") <= 1 and 0.0 <= float(x) <= 1.0
                )
            ),
        ),
    )
    @settings(max_examples=200, deadline=None)
    def test_confidence_parsing_properties(self, confidence_input: Any) -> None:
        """Property: Confidence field should correctly parse various numeric input types
        to float.
        """
        signal = TradeSignal(
            symbol=BTC_HL,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=Decimal("100.0"),
            exchange=ExchangeName.HYPERLIQUID,
            confidence=confidence_input,
        )

        # Property: Confidence should be converted to float
        assert isinstance(signal.confidence, float)
        assert 0.0 <= signal.confidence <= 1.0

    @given(
        timestamp_input=st.one_of(
            valid_timestamp_strategy(),
            st.integers(
                min_value=946684800,  # 2000-01-01
                max_value=1893456000,  # 2030-01-01
            ),
        ),
    )
    @settings(max_examples=150, deadline=None)
    def test_timestamp_parsing_properties(self, timestamp_input: Any) -> None:
        """Property: Timestamp fields should parse various input types correctly."""
        signal = TradeSignal(
            symbol=BTC_HL,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=Decimal("100.0"),
            exchange=ExchangeName.HYPERLIQUID,
            timestamp=timestamp_input,
        )

        # Property: Timestamp should be converted to UTC datetime
        assert isinstance(signal.timestamp, datetime)
        assert signal.timestamp.tzinfo == UTC

    @given(
        exchange_list=st.lists(
            st.sampled_from(list(ExchangeName)), min_size=1, max_size=3, unique=True
        ),
    )
    @settings(max_examples=100, deadline=None)
    def test_exchange_list_validation_properties(self, exchange_list: list[ExchangeName]) -> None:
        """Property: Exchange field should handle lists of exchanges correctly."""
        signal = TradeSignal(
            symbol=BTC_HL,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=Decimal("100.0"),
            exchange=exchange_list,
        )

        # Property: Exchange list should be preserved
        assert signal.exchange == exchange_list
        assert isinstance(signal.exchange, list)
        assert len(signal.exchange) == len(exchange_list)

        # Property: All items should be ExchangeName enums
        for exchange in signal.exchange:
            assert isinstance(exchange, ExchangeName)

    @given(
        invalid_timestamp=st.one_of(
            st.just("not_a_datetime"),
            st.just("2023-13-01T00:00:00Z"),  # Invalid month
            st.just("2023-02-30T00:00:00Z"),  # Invalid day
            st.just("invalid_date_string"),
            st.just([]),  # Wrong type
        ),
    )
    @settings(max_examples=100, deadline=None)
    def test_invalid_timestamp_rejection_properties(self, invalid_timestamp: Any) -> None:
        """Property: Invalid timestamp inputs should always raise ValidationError."""
        with pytest.raises((ValidationError, DateTimeParsingError, TimestampFormatError)):
            TradeSignal(
                symbol=BTC_HL,
                signal_type=SignalType.ENTER_LONG,
                side=OrderSide.BUY,
                price=Decimal("100.0"),
                exchange=ExchangeName.HYPERLIQUID,
                timestamp=invalid_timestamp,
            )

    @given(
        invalid_exchange=st.one_of(
            st.just([]),  # Empty list
            st.just(""),  # Empty string
            st.just(123),  # Wrong type
            st.lists(st.integers(), min_size=1, max_size=3),  # List of wrong types
        ),
    )
    @settings(max_examples=100, deadline=None)
    def test_invalid_exchange_rejection_properties(self, invalid_exchange: Any) -> None:
        """Property: Invalid exchange inputs should always raise ValidationError."""
        with pytest.raises((ValidationError, ListFieldError, TypeFieldError)):
            TradeSignal(
                symbol=BTC_HL,
                signal_type=SignalType.ENTER_LONG,
                side=OrderSide.BUY,
                price=Decimal("100.0"),
                exchange=invalid_exchange,
            )


# =============================================================================
# TRADE SIGNAL BUSINESS LOGIC PROPERTIES
# =============================================================================


class TestTradeSignalBusinessLogicProperties:
    """Property-based tests for TradeSignal business logic and relationships."""

    @given(
        symbol=valid_symbol_strategy(),
        price=price_strategy(),
        stop_loss=price_strategy(),
        take_profit=price_strategy(),
    )
    @settings(max_examples=150, deadline=None)
    def test_stop_loss_take_profit_relationships_properties(
        self,
        symbol: Any,
        price: Decimal,
        stop_loss: Decimal,
        take_profit: Decimal,
    ) -> None:
        """Property: Test logical relationships between price, stop_loss, and take_profit."""
        # For LONG positions (BUY)
        signal_long = TradeSignal(
            symbol=symbol,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            exchange=ExchangeName.HYPERLIQUID,
        )

        # Property: All prices should be positive (validated by model)
        assert signal_long.price > 0
        if signal_long.stop_loss is not None:
            assert signal_long.stop_loss > 0
        if signal_long.take_profit is not None:
            assert signal_long.take_profit > 0

        # For SHORT positions (SELL)
        signal_short = TradeSignal(
            symbol=symbol,
            signal_type=SignalType.ENTER_SHORT,
            side=OrderSide.SELL,
            price=price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            exchange=ExchangeName.HYPERLIQUID,
        )

        # Property: All prices should be positive (validated by model)
        assert signal_short.price > 0
        if signal_short.stop_loss is not None:
            assert signal_short.stop_loss > 0
        if signal_short.take_profit is not None:
            assert signal_short.take_profit > 0

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
    )
    @settings(max_examples=200, deadline=None)
    def test_signal_consistency_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
    ) -> None:
        """Property: Signal type and side should maintain logical consistency."""
        signal = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
        )

        # Property: ENTER_LONG typically pairs with BUY, ENTER_SHORT with SELL
        # But the model doesn't enforce this - it's strategy dependent
        # So we just verify the fields are preserved correctly
        assert signal.signal_type == signal_type
        assert signal.side == side

        # Property: Trading signals should have positive prices
        assert signal.price > 0

    @given(
        symbol=valid_symbol_strategy(),
        signal_type=signal_type_strategy(),
        side=order_side_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
        quantity=quantity_strategy(),
        confidence=confidence_strategy(),
        metadata=metadata_strategy(),
    )
    @settings(max_examples=150, deadline=None)
    def test_signal_enrichment_properties(
        self,
        symbol: Any,
        signal_type: SignalType,
        side: OrderSide,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
        quantity: Decimal,
        confidence: float,
        metadata: dict[str, Any],
    ) -> None:
        """Property: Signals should support enrichment by downstream systems."""
        # Create minimal signal
        signal = TradeSignal(
            symbol=symbol,
            signal_type=signal_type,
            side=side,
            price=price,
            exchange=exchange,
        )

        # Property: Signal can be enriched with additional data
        signal.quantity = quantity
        signal.confidence = confidence
        signal.metadata = metadata

        # Property: Enriched data should be preserved
        assert signal.quantity == quantity
        assert signal.confidence == confidence
        assert signal.metadata == metadata

        # Property: Original fields should remain unchanged
        assert signal.symbol == symbol
        assert signal.signal_type == signal_type
        assert signal.side == side
        assert signal.price == price
        assert signal.exchange == exchange


# =============================================================================
# EDGE CASE AND INTEGRATION PROPERTIES
# =============================================================================


class TestTradeSignalEdgeCaseProperties:
    """Property-based tests for edge cases and integration scenarios."""

    @given(
        symbol=valid_symbol_strategy(),
        source_strategy=strategy_name_strategy(),
    )
    @settings(max_examples=150, deadline=None)
    def test_signal_id_uniqueness_properties(
        self,
        symbol: Any,
        source_strategy: str,
    ) -> None:
        """Property: Each signal should have a unique ID."""
        signals = []

        # Generate multiple signals
        for _ in range(10):
            signal = TradeSignal(
                symbol=symbol,
                signal_type=SignalType.ENTER_LONG,
                side=OrderSide.BUY,
                price=Decimal("100.0"),
                exchange=ExchangeName.HYPERLIQUID,
                source_strategy=source_strategy,
            )
            signals.append(signal)

        # Property: All signal IDs should be unique
        signal_ids = [signal.signal_id for signal in signals]
        assert len(signal_ids) == len(set(signal_ids))

        # Property: All signal IDs should be valid UUIDs
        for signal_id in signal_ids:
            assert isinstance(uuid.UUID(signal_id), uuid.UUID)

    @given(
        symbol=valid_symbol_strategy(),
        price=price_strategy(),
        exchange=exchange_strategy(),
        metadata=metadata_strategy(),
    )
    @settings(max_examples=150, deadline=None)
    def test_signal_serialization_properties(
        self,
        symbol: Any,
        price: Decimal,
        exchange: ExchangeName | list[ExchangeName],
        metadata: dict[str, Any],
    ) -> None:
        """Property: Signals should be serializable and deserializable."""
        signal = TradeSignal(
            symbol=symbol,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=price,
            exchange=exchange,
            metadata=metadata,
        )

        # Property: Signal should be serializable to dict
        signal_dict = signal.model_dump()
        assert isinstance(signal_dict, dict)

        # Property: Essential fields should be present in serialized data
        assert "symbol" in signal_dict
        assert "signal_type" in signal_dict
        assert "side" in signal_dict
        assert "price" in signal_dict
        assert "exchange" in signal_dict

        # Property: Signal should be serializable to JSON
        json_str = signal.model_dump_json()
        assert isinstance(json_str, str)
        assert len(json_str) > 0

    @given(
        symbol=valid_symbol_strategy(),
        base_time=valid_timestamp_strategy(),
        offset_seconds=st.integers(min_value=-3600, max_value=3600),
    )
    @settings(max_examples=150, deadline=None)
    def test_signal_timing_edge_cases_properties(
        self,
        symbol: Any,
        base_time: datetime,
        offset_seconds: int,
    ) -> None:
        """Property: Signal timing should handle various edge cases correctly."""
        expiration_time = base_time + timedelta(seconds=offset_seconds)

        signal = TradeSignal(
            symbol=symbol,
            signal_type=SignalType.ENTER_LONG,
            side=OrderSide.BUY,
            price=Decimal("100.0"),
            exchange=ExchangeName.HYPERLIQUID,
            timestamp=base_time,
            expiration=expiration_time,
        )

        # Property: Timestamp relationships should be preserved
        assert signal.timestamp == base_time
        assert signal.expiration == expiration_time

        # Property: Time difference should match our offset
        time_diff = signal.expiration - signal.timestamp
        assert time_diff.total_seconds() == offset_seconds
